# -*- coding: utf-8 -*-
"""HH_Pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jl9MHu_h5VFgA_0iVFdfwBXhaUL5rTe6
"""

from keras.models import Sequential
from keras.layers import Dense, Input, Activation, Dropout
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

train_dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/HH.csv')
pred_dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/HH_Pred.csv')

x_train = train_dataset.transpose()[:-3]
y_train = train_dataset.transpose()[-3:]
x_train = x_train.transpose()
y_train = y_train.transpose()

x_pred = pred_dataset

model = Sequential()
Input(shape=(21, ))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(3))

model.compile(loss='mae', optimizer = 'adam')
model.fit(x_train, y_train, epochs=1500, batch_size=12)

y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)